default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: eefio_api_development

test:
  <<: *default
  database: eefio_api_test

production:
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
