default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: ethio_api_development

test:
  <<: *default
  database: ethio_api_test

production:
  <<: *default
  database: ethio_api_production
  username: ethio_wwi
  password: <%= ENV['ETHIO_API_DATABASE_PASSWORD'] %>
