default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: eefio_api_development

test:
  <<: *default
  database: eefio_api_test

production:
  <<: *default
  database: eefio_api_production
  username: eefio_wwi
  password: <%= ENV['ETHIO_API_DATABASE_PASSWORD'] %>
