#!/usr/bin/env ruby

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

require 'pathname'
require 'fileutils'
include FileUtils

# Path to your application root
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n==> Command #{args} failed")
end

chdir APP_ROOT do
  # Ensure everything in the app is up to date
  system! 'script/update'

  # Run tests
  if ARGV[0].nil?
    # Print output at the start of test run
    puts "Running tests at #{Time.now.strftime("%H:%M:%S")}…"
    system! 'bundle exec rspec'

    puts '==> Running Rubocop…'
    system! 'bundle exec rubocop'
  else
    # Pass arguments to test call. This is useful for calling a single test.
    puts "==> Running test: #{ARGV[0]}"
    system! "bundle exec rspec #{ARGV[0]}"

    puts '==> Running Rubocop…'
    system! "bundle exec rubocop #{ARGV[0]}"
  end
end
